#!/usr/bin/env bash
#
# Rename a git branch.

[[ $1 ]] || exit 1

new_name="$1"
old_name="$(git rev-parse --abbrev-ref HEAD)"

git branch -m "${new_name}"
git push origin -u "${new_name}"
git push origin --delete "${old_name}"
